[package]
edition = "2018"
name = "${TFSCLIENT_NAME}"
version = "${TFSCLIENT_VERSION}"
authors = ["${TFSCLIENT_AUTHOR}"]
license = "${TFSCLIENT_LICENSE}"
description = "${TFSCLIENT_DESCRIPTION}"
readme = "README.md"
homepage = "${TFSCLIENT_URL}"
repository = "${TFSCLIENT_URL}"
documentation = "https://docs.rs/${TFSCLIENT_NAME}"
categories = ["api-bindings", "science"]

[dependencies]
futures = "0.1.25"
grpcio = "${TFSCLIENT_VERSION_GRPC_RUST}"
protobuf = "${TFSCLIENT_VERSION_PROTO_RUST}"

[lib]
crate-type = ["rlib"]
